# Generated by Django 4.2.26 on 2025-11-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='tube_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='tube_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
