# Generated by Django 4.2.26 on 2025-11-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_test_tube_color_test_tube_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='tube_color',
        ),
        migrations.RemoveField(
            model_name='test',
            name='tube_name',
        ),
        migrations.AddField(
            model_name='test',
            name='tubes',
            field=models.ManyToManyField(blank=True, related_name='tests', to='tests.tube'),
        ),
    ]
