# Generated by Django 4.2.26 on 2025-11-14 18:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_alter_lab_phone'),
        ('tests', '0003_tube_remove_test_tube_color_remove_test_tube_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tube',
            name='color',
        ),
        migrations.AddField(
            model_name='tube',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tube',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_tubes', to='labs.lab'),
        ),
    ]
