# Generated by Django 4.2.26 on 2025-11-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_patienttest_lab_alter_report_lab'),
        ('accounts', '0002_alter_customuser_lab'),
        ('patients', '0002_alter_patient_lab'),
        ('billing', '0002_alter_bill_lab'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lab',
        ),
    ]
