# Generated by Django 4.2.26 on 2025-11-11 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
        ('reports', '0002_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttest',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_tests', to='labs.lab'),
        ),
        migrations.AlterField(
            model_name='report',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='labs.lab'),
        ),
    ]
