# Generated by Django 4.2.26 on 2025-11-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='contact_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
