# Generated by Django 4.2.26 on 2025-11-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_alter_lab_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
