# Generated by Django 4.2.26 on 2025-11-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_lab_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
